#version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["db"]
    container_name: py-app-container
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always

  db:
    image: mysql:8
    container_name: db-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # it's very important!!!
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always
    

#  prometheus:
#    image: prom/prometheus:v2.47.2
#    container_name: prometheus
#    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus:/etc/prometheus/
#      - prometheus-data:/prometheus/
#    networks:
#      - backend
#    restart: always

#volumes:
#  prometheus-data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
#      - gateway: 172.17.0.1
