version: '3.8'
include:
- ./proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on: ["db"]
    container_name: py-app
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always

  db:
    image: mysql:8
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_ROOT_HOST="%" # it's very important!!!
    ports:
      - 3306:3306
    volumes:
      - ~/dbdata:/var/lib/mysql/
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always

networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24

